### ISSUE TITLE
Not getting any errors with kotlin-android

### ISSUE THREAD

**Issue by eygraber** [chao2zhang/RequireNamedArgument#2]
Not sure if this is related to using Android or not, but I'm not seeing any error for a function annotated with `RequireNamedArgument` that is not using named arguments.

Kotlin 1.5.30 and Gradle 7.2

**Comment by eygraber** [comment]
I must've done something wrong before, because it is working now.

**Comment by picklebento** [comment]
I will update the Kotlin and Gradle dependencies.
